### ISSUE TITLE
Example for mjml4j

### ISSUE THREAD

**Issue by gopikrishnasyla** [ed0906/mjml4j#1]
Thanks Ed for sharing this wrapper. Could please provide an example on how to use this to create responsive html dynamically. 
Also, I am new to gradle, can you please provide a maven project or add how to convert from gradle to POM.
Thanks a lot.
Syla

**Comment by ed0906** [comment]
Hi @gopikrishnasyla Cheers for looking into it :) At the moment its just a Java wrapper around the MJML [API](https://mjml.io/api) so you will need to create your MJML document seperately and feed it in similar to how the [ReadMe](https://github.com/ed0906/mjml4j/blob/master/README.MD) shows.

I'll try and add equivelent Maven dependency config this evening :)

**Comment by gopikrishnasyla** [comment]
@ed0906 Thanks for quick reply :)

**Comment by ed0906** [comment]
@gopikrishnasyla I've added maven configuration for the dependency to the Read Me :)

**Comment by gopikrishnasyla** [comment]
@ed0906 Thanks. If possible, can you pls add full pom file so that I can import the project to eclipse as maven project. Sorry for that.
Also,
I have query: Why do we need to use application ID and key?

Cheers,
Syla

**Comment by ed0906** [comment]
@gopikrishnasyla I'm not much of a maven user myself so I'll have to go away and learn the pom structure.

The key bit really if you were to build a pom is:

```
// Application Name + Version
def VERSION = '0.1.2'
def GROUP = 'ifusion'
def NAME = 'mjml-client'

dependencies {
    // Compile time (Production) dependencies 
    compile group: 'com.fasterxml.jackson.core', name: 'jackson-databind', version: '2.8.8.1'
    compile group: 'org.apache.httpcomponents', name: 'httpclient', version: '4.5.3'
    compile group: 'commons-io', name: 'commons-io', version: '2.5'

    // Test dependencies
    testCompile 'junit:junit:4.11'
    testCompile group: 'org.assertj', name: 'assertj-core', version: '3.8.0'
    testCompile group: 'com.github.tomakehurst', name: 'wiremock', version: '2.6.0'
    testCompile group: 'commons-cli', name: 'commons-cli', version: '1.4'
}
```

The reason for the Application ID and Key is that this java client talks to the official [MJML API](https://mjml.io/api/) which requires both those parameters as authentication. You can register for an `Application ID` and `Key` [here](https://mjml.io/api/). It's free and a very simple request process :)

**Comment by gopikrishnasyla** [comment]
@ed0906 Thank you. That helps.
